apiVersion: v2
publisher: vuejs
name: vetur
version: 0.25.0
type: VS Code extension
displayName: Vetur
title: Rich Vue.js support
description: Vue tooling for VS Code
icon: https://upload.wikimedia.org/wikipedia/commons/9/95/Vue.js_Logo_2.svg
repository: https://github.com/vuejs/vetur.git
category: Language
firstPublicationDate: "2019-07-02"
spec:
  containers:
    - image: "sds.redii.net/eclipse-che/che-sidecar-node:10-0cb5d78"
      name: vscode-vetur
      memoryLimit: '256Mi'
  extensions:
    - https://github.com/vuejs/vetur/releases/download/v0.25.0/vetur-0.25.0.vsix
